export const discountData = [
  {
    id: "1",
    img: "/images/discounted/discount-1.png",
    title: "Headphone",
    originalPrice: "233.00",
    discountedPrice: "209.70",
  },
  {
    id: "2",
    img: "/images/discounted/discount-2.png",
    title: "TCL TV 1920p",
    originalPrice: "320.00",
    discountedPrice: "280.40",
  },
  {
    id: "3",
    img: "/images/discounted/discount-3.png",
    title: "PS4",
    originalPrice: "220.00",
    discountedPrice: "170.50",
  },
  {
    id: "4",
    img: "/images/discounted/discount-4.png",
    title: "Setgear",
    originalPrice: "124.00",
    discountedPrice: "111.20",
  },
  {
    id: "5",
    img: "/images/discounted/discount-5.png",
    title: "Sony Speaker",
    originalPrice: "290.80",
    discountedPrice: "269.70",
  },
  {
    id: "6",
    img: "/images/discounted/discount-6.png",
    title: "RG Product",
    originalPrice: "360.70",
    discountedPrice: "240.10",
  },
  {
    id: "7",
    img: "/images/discounted/discount-7.png",
    title: "Panasonic Disk",
    originalPrice: "233.00",
    discountedPrice: "209.70",
  },
  {
    id: "8",
    img: "/images/discounted/discount-8.png",
    title: "Drive",
    originalPrice: "240.00",
    discountedPrice: "209.70",
  },
  {
    id: "9",
    img: "/images/discounted/discount-9.png",
    title: "CCTV",
    originalPrice: "233.00",
    discountedPrice: "209.70",
  },
];
