import { ReactNode } from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@mui/material";

import theme from "@/theme";
import "../../app/globals.css";
import Header from "@/components/layout/header";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface PropsTypes {
  children: ReactNode;
}

export default function UserLayout({ children }: Readonly<PropsTypes>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={poppins.className}>
          <header>
            <Header />
          </header>
          <main style={{ minHeight: "100vh", background: "#f5f5f5" }}>{children}</main>
          <footer>Footer</footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
