export const flashProductsData = [
  {
    id: "1",
    image: "/images/flash-deals/flash-1.png",
    name: "Nike Courte Zoom Vapor Cage",
    rating: 4,
    originalPrice: "250.00",
    discountedPrice: "187.50",
  },
  {
    id: "2",
    image: "/images/flash-deals/flash-2.png",
    name: "Classic Rolex Watch",
    rating: 4.5,
    originalPrice: "350.00",
    discountedPrice: "297.50",
  },
  {
    id: "3",
    image: "/images/flash-deals/flash-3.png",
    name: "Iphone 13 pro max",
    rating: 4,
    originalPrice: "1250.00",
    discountedPrice: "1040.50",
  },
  {
    id: "4",
    image: "/images/flash-deals/flash-4.png",
    name: "Mi Led Smart Watch",
    rating: 3.5,
    originalPrice: "180.00",
    discountedPrice: "142.40",
  },
  {
    id: "5",
    image: "/images/flash-deals/flash-1.png",
    name: "Nike Courte Zoom Vapor Cage",
    rating: 4,
    originalPrice: "250.00",
    discountedPrice: "187.50",
  },
  {
    id: "6",
    image: "/images/flash-deals/flash-2.png",
    name: "Classic Rolex Watch",
    rating: 4.5,
    originalPrice: "350.00",
    discountedPrice: "297.50",
  },
  {
    id: "7",
    image: "/images/flash-deals/flash-3.png",
    name: "Iphone 13 pro max",
    rating: 4,
    originalPrice: "1250.00",
    discountedPrice: "1040.50",
  },
  {
    id: "8",
    image: "/images/flash-deals/flash-4.png",
    name: "Mi Led Smart Watch",
    rating: 3.5,
    originalPrice: "180.00",
    discountedPrice: "142.40",
  },
];
